version: "3.5"

services:
  workspaces:
    image: campr-Project-Management/campr:latest
    shm_size: 1g
    ports:
    - "80:80"
    env_file: config/.env
    volumes:
    - ./config/workspaces/backend/app/config/parameters.yml:/app/backend/app/config/parameters.yml
    - workspaces-static-js:/app/web/static/js/
    - workspaces-uploads:/app/web/uploads
    extra_hosts:
    - "portal:127.0.0.1"
    - "workspaces:127.0.0.1"

  mailcatcher:
    image: schickling/mailcatcher
    ports:
    - "1080:1080"
    env_file: config/.env

  mysql:
    image: mysql:5.7
    volumes:
    - onpremise-data:/var/lib/mysql
    - ./config/mysql/mysql.cnf:/etc/mysql/conf.d/docker.cnf
    ports:
    - "3306:3306"
    env_file: config/.env

  redis:
    image: redis
    env_file: config/.env
    ports:
    - "6379:6379"
    
volumes:
  onpremise-data:
  workspaces-static-js:
  workspaces-uploads:
